name: Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * 1"
jobs:
  maintenance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
