name: Status Reader
on:
  workflow_dispatch:
    inputs:
      job_id:
        description: "Job ID"
        required: true
jobs:
  status-reader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print status file
        run: cat "jobs/status/${{ github.event.inputs.job_id }}.status.json"
